version: '3'
services:
 mysql_db:
  image: mysql
  container_name: db
  restart: always
  environment:
   MYSQL_DATABASE: 'achatdb'
   MYSQL_ROOT_PASSWORD: 'password1'
  ports:
   - '3306:3306'
  volumes:
   - db:/var/lib/mysql
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: unless-stopped
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: mysql_db
  depends_on:
  - mysql_db
  ports:
   - '8068:80'
 spring_app:
  image: mejriali/achat-1.1
  container_name: achat
  restart: on-failure
  ports:
   - 8089:8089
  depends_on:
   - mysql_db
  volumes:
   - achat_cache:/sonar-nexus/achatapp-cache

volumes:
 db:
 achat_cache:
