version: "3"
services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    ports:
      - '3306:3306'
 spring_app:
  image: mejriali/achat-1.1:5
  container_name: achat
  restart: on-failure
  ports:
   - 8089:8089
    environment :
      -SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      -SPRING_DATASOURCE_USERNAME : root

    depends_on:
      - mysqldb