version: "3"
services: 
  mysqldb: 
    container_name: mysqldb
    environment: 
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: "123456"
    image: mysql
    ports: 
      - "3306:3306"
    restart: unless-stopped
    volumes: 
      - "db:/var/lib/mysql"
  app: 
    container_name: achat_container
    image: hadilchahba/achat
    ports: 
      - "8089:8089"
    restart: on-failure
    volumes: 
      - "m2:/root/.m2"
volumes: 
  db:
  m2: 