version: '3'
services:
 sonarqube:
  image: sonarqube:8.9.7-community
  ports:
  - "9000:9000"
  volumes:
  - 'SonarQube_data:/opt/SonarQube/data'
  - 'SonarQube_extensions:/opt/SonarQube/extensions'
  - 'SonarQube_logs:/opt/SonarQube/logs'
 nexus:
  image: sonatype/nexus3
  ports:
  - "8081:8081"
  volumes:
  - 'nexus-data:/nexus-data'
 mysqldb:
  image: mysqldb
  container_name: db
  restart: always
  environment:
   MYSQL_DATABASE: 'achatdb'
   MYSQL_ROOT_PASSWORD: 'root'
  ports:
   - '3306:3306'
  volumes:
   - db:/var/lib/mysql
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: unless-stopped
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: mysqldb
  depends_on:
  - mysqldb
  ports:
   - '8068:80'
 spring_app:
  image: mejriali/achat-1.1:31
  container_name: achat
  restart: on-failure
  ports:
   - 8089:8089
  depends_on:
   - mysqldb
  volumes:
   - achat_cache:/sonar-nexus/achatapp-cache



volumes:
 SonarQube_data:
 SonarQube_extensions:
 SonarQube_logs:
 nexus-data:
 db:
 achat_cache: