version: '3.3'
services:
  mysqldb:
    
    image: mysql:latest
    volumes:
      - mysql_container:/var/lib/mysql:rw
    user: root
    restart: always
    ports:
      - 3308:3306
    environment:

       MYSQL_DATABASE: achat-db
       MYSQL_ALLOW_EMPTY_PASSWORD: 1


  spring_app:
    depends_on:
      - mysqldb
    image: mejriali/achat-1.1:5
    ports:
      - 8089:8089
    restart: unless-stopped
    links:
      - mysqldb:mysqldb

volumes:
  mysql_container: { }