version: "3"
services:
  mysql-standalone:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
    restart : on-failure
  achatproject:
    image: wagine/achat:latest
    ports:
      - 8089:8089
    restart: unless-stopped
    environment :
      -SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/achatdb?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      -SPRING_DATASOURCE_USERNAME : root
    depends_on:
      - mysql-standalone
    links:
      - mysql-standalone:mysql-standalone
