version: "3.4"
services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    ports:
      - '3306:3306'
  backend:
    image: mejriali/achat-1.1:31
    ports:
      - '8089:8089'
    restart: on-failure
    environment :
      -SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      -SPRING_DATASOURCE_USERNAME : root

    depends_on:
      - mysqldb