version: '3.3'
services:
 mysql_db:
  image: mysql
  container_name: db
  restart: always
  environment:
   MYSQL_DATABASE: 'achatdb'
   MYSQL_ROOT_PASSWORD: 'root'
  ports:
   - '3306:3306'
  volumes:
   - db:/var/lib/mysql
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: unless-stopped
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: mysql_db
  depends_on:
  - mysql_db
  ports:
   - '8068:80'
  spring_app:
    depends_on:
      - mysqldb1
    image: mejriali/achat-1.1
    ports:
      - 8089:8089
    restart: always
    container_name: spring_app

volumes:
 db: